### ISSUE TITLE
Not compatible with python 3.7

### ISSUE THREAD

**Issue by dzervas** [tabahi/Octoprint-Filament-Motion-Sensor#1]
Due to gpiod the minimum supported python version is 3.9. The problem is that I can't get my octopi (v0.17.0 with octoprint 1.10.2) to install python 3.9 or newer. It's based on raspbian (debian) buster and has no python 3.9 backport

**Comment by tabahi** [comment]
gpiod had a major update after python 3.8. The script differs a lot, which makes it backward incompatible. If you can't update your octoprint then it's better to simply use the older forks with RPi.GPIO support.

https://github.com/hviet17/Octoprint-Smart-Filament-Sensor
